### ISSUE TITLE
How to make a portable binary for Windows and Linux

### ISSUE THREAD

**Issue by TheRealMrWicked** [MatrixEditor/samloader3#2]
Hey this is not related to your project specifically, in that I do not know how to do it for any python project. I would like to make a binary (.exe) of this project that can be taken from one computer to another but I dont know how.

I tried to use pyinstaller but it always fails, can you help me with this issue or give any advice.

Thank you in Advance

**Comment by MatrixEditor** [comment]
In essence, [pyInstaller](https://github.com/pyinstaller/pyinstaller)  only extracts the relevant executables from the binary and runs them in another process. Therefore, using this package does not make a huge difference to installing python globally. 

A possible workaround could be a portable python installation for environments that don't allow new programs to be installed.

**Comment by RealMrWicked** [comment]
Interesting, this isn't exactly what I had in mind, I'm a very traditional programmer. In that I believe a binary should have as little dependencies as possible.

A good example would be, if you are familiar with the .NET framework for C#. There are two kinds of binaries that can be produced, ones that include the framework within and those that do not.

Though it makes the size bigger, a self contained binary is good because the user does not need to install anything else, not a portable python install, a framework or anything else.

I don't fully understand how interpreted languages works vs complied ones, so I am not sure what the limit is here, but either way.

Thank you for you help.
